### PR TITLE
navigate tag,link,todo,headers and incremental search,saved search etc.

### PR DESCRIPTION
**Pull request by cnshsliu**
## Proposed change

1. Note structure (tags, links, todos) and hierarchy (parent and children) navigation
2. Search notes incrementally, by either tag or content
3. Search an AND or OR query (match all words or any of them)
4. Exclude words (match those, but not these)
5. Saved search history, easily pick up again.
6. Headers outline and jumping

## Type of change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [x] Code quality improvements to existing code or addition of tests
- [x] Documentation update

## Additional information

- This PR fixes or closes issue: fixes # 
- This PR is related to issue: #210  #23

## Checklist

- [x] I am running the **latest** version of the plugin.
- [x] The code change is tested and works locally.
- [ ] There is no commented out code in this PR.
- [x] The code has been formatted using Stylua (a `.stylua.toml` file is provided)
- [x] The code has been checked with luacheck (a `.luacheckrc` file is provided)
- [ ] The `README.md` has been updated according to this change.
- [x] The `doc/telekasten.txt` helpfile has been updated according to this change.

### CODE REVIEW

**Comment by lambtho12** [comment]
Awesome! Thank you for this PR. I will try to set aside some time on Wednesday to review it.

**Comment by cnshsliu** [comment]
> 

thanks a lot.

**Comment by cnshsliu** [comment]
Finally, I decided  to release a standalone plugin for these functions to avoid injecting too many codes into telekasten.nvim

**Comment by lambtho12** [comment]
Can you share the repo for this standalone plugin? 

I am personally ok with integrating this directly to telekasten, but maybe it would be better to first refactor the code base a bit in order to simplify maintenance before bringing in such a large piece of work.

**Comment by cnshsliu** [comment]
> 

Allow me several days to clear up, will share repo later. 😀

**Comment by cnshsliu** [comment]
Here it is:  https://github.com/cnshsliu/smp.nvim

**Pull request closed without merging**
