### PR TITLE
fix:fix show hello when open nvim in topleft

### PR DESCRIPTION
**Pull request by zhaogangang**
## Proposed change

x-special/nautilus-clipboard
copy
file:///var/run/vmblock-fuse/blockdir/ZNZ9a9/1675406331282.mp4

image
thie image is open nvim

## Type of change

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Documentation update

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:

## Checklist

- [x] I am running the **latest** version of the plugin.
- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [ ] The code has been formatted using Stylua (a `.stylua.toml` file is provided)
- [ ] The code has been checked with luacheck (a `.luacheckrc` file is provided)
- [ ] The `README.md` has been updated according to this change.
- [ ] The `doc/telekasten.txt` helpfile has been updated according to this change.

### CODE REVIEW

**Comment by zhaogangang** [comment]
i don't know why &> /dev/null print hello, i test in my nvim lua env, it's print hello, just like this
image

**Comment by renerocksai** [comment]
Thanks! I've never seen `&>` syntax before, not sure why it was in there. Thanks for fixing it!

**Comment by lambtho12** [comment]
My bad. I do not know why I wrote it like that. Probably some poor yank/paste or something... Thank you for fixing it.

**Comment by zhaogangang** [comment]
actually '&>' syntax is right in some version,i test in my bash, it work well, but in nvim lua env, this not work

**Pull request merged**
