### PR TITLE
Fix daily/weekly create behavior

### PR DESCRIPTION
**Pull request by ernie**
## Proposed change

~I believe the find_daily_notes and find_weekly_notes were erroneously creating a note for the current day/week.~ (edit: this was apparently intentional?) This seems unintentional, given that GotoToday and GotoThisWeek exist, which would be a more intuitive trigger for autocreate. Additionally, the behavior for GotoToday was looking at create on follow configuration instead of create dailies configuration.

## Type of change

- [X] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Documentation update

## Additional information

- This PR fixes or closes issue: fixes #
- This PR is related to issue:

## Checklist

- [x] I am running the **latest** version of the plugin.
- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [x] The code has been formatted using Stylua (a `.stylua.toml` file is provided)
- [ ] The code has been checked with luacheck (a `.luacheckrc` file is provided)
- [x] The `README.md` has been updated according to this change.
- [ ] The `doc/telekasten.txt` helpfile has been updated according to this change.

### CODE REVIEW

**Comment by lambtho12** [comment]
I tend to agree with you. This is a somewhat useless feature.
Is it even possible to create a note from a picker to begin with? As soon as you have a few notes the picker will always find something "close enough", especially considering the fixed naming convention for daily/weekly notes...
I think this argument is also more or less valid for regular notes. Except if your new title is _very_ different from all other notes (increasingly unlikely the more you use TK), telescope will always have something to propose for what you type. The more elegant way to do (imo) would be to have a picker action to create the note from the `find_note` picker if we are not satisfied with what telescope returns (that can be done as a second, separate PR though).


@renerocksai , do you have a moment to weight in on that PR?

In any case, this PR is incomplete. If we remove the option to create non-existing notes from these functions, we should completely remove the options from the code (defaults, setup), as well as update the doc and the README to remove it there too.

**Comment by ernie** [comment]
@lambtho12 This only removes it from the note search feature, which shouldn't be creating a note when I'm looking for one. I do find it useful in the case I want to take a daily/weekly note -- in those cases, I will use the `goto_today` or `goto_thisweek` mappings, or perhaps select a date from the calendar, all of which trigger note creation if absent -- so the options still make sense.

**Comment by lambtho12** [comment]
@ernie I agree with you on the principle, but this is not how it is implemented. 

`goto_today`and `goto_thisweek`both call `GotoDate`which only looks for `follow_creates_nonexisting`and not `dailies_create_nonexisting`or `weeklies_create_nonexisting`.
The latter two are only used in for `FindDailyNotes`and `FindWeeklyNotes`and this PR specifically removes them. Hence `weeklies_create_nonexisting`and `dailies_create_nonexisting`should be completely removed as well.

Now, maybe this is an implementation issue, and `GotoDate`should actually look correctly for `dailies_create_nonexisting` or `weeklies_create_nonexisting`, as it is suggested in the [Readme](https://github.com/renerocksai/telekasten.nvim/blob/17542ee617ad811c7efc26fc77d771129192b03f/README.md?plain=1#L717-L720).

**Comment by lambtho12** [comment]
My bad. It seems that I completely missed that, I don't know why... Probably because the coffee machine was in reparation.

Although, the README and docs should still be updated. [See here](https://github.com/renerocksai/telekasten.nvim/pull/128) for instance.

**Comment by ernie** [comment]
Oh, shoot! You're right, it was documented behavior. That makes the behavior seem even more bizarre to me -- I thought it was an oversight before.

**Comment by lambtho12** [comment]
I think it makes sense, but it does not work. Just as for `find_note`.

Example workflow:
1. You remember that on 2022-04-12 you called a contractor for a project and want to find the notes you took in your journal related to that call
2. You use `find_daily_notes` and look for that date. As it does not exist, you want to create the note on the spot and fill what you remember for the next time.

The actual issue (I think after a very minimal testing) is that if you already have entries for 2022, or for April for instance, Telescope will always find something "close enough" and propose a note in the list. So you will not be able to create the note on the spot (I think).

---
Same example with `find_note`:
1. I want to look at a note regarding "coaxial rotors"
2. As I already have notes regarding "coaxial gears" and "helicopter rotors", telescope will propose me these two notes and I will not be able to create the missing note (or at least I think so).

**Comment by ernie** [comment]
Yeah, makes sense. I guess for my workflow, I can't imagine a case where I'd look for a date in the past and then want to create a pre-dated note on the spot. I don't trust present-me's memory of past-me's experience in that case. But I may be unique in that. I can always use my own fork if that's the case.

The "problem" I wanted to address here was the documented behavior -- specifically, it made no sense to me that every time I went to search for a daily note (say, a note from the distant past) I would create a note for **today**. If I was just searching for a past note, that note for today would now exist and be forever an empty copy of my template.

**Comment by lambtho12** [comment]
@renerocksai , before migrating to SH, could you look into this PR, as well as #123  and #122? It would be a shame to loose all the work done by @ernie on these improvements.

**Comment by renerocksai** [comment]
The intended use-case was (and this worked at some stage): I have, e.g. a note template (weekly) with a `{{thursday}}` link in it. If I follow that link on a wednesday, it should create thursday's note. Since the file check is done before the picker is presented, this has nothing to do with telescope finding a file or not. 

This feature might have stopped working because of previous work wrt. dailies, weeklies, paths, etc.

IMHO we should rather make it work than remove it. Also, probably the docs should have been more clear in the first place to avoid confusion. My bad.

**Comment by renerocksai** [comment]
I want to re-iterate:

- no telescope picker creates anything
- it doesn't matter what you type in the picker, nothing will be created
- file presence and flag checks are done before the picker is presented
- hence, when following a [[link]] (or date...), the picker will find exactly that if creation flags allow for it
- if you disable the corresponding flags, nothing will be created 

Can someone please explain to me a use-case where the plugin gets in the way that cannot be fixed by setting a flag to false. I am having difficulties to understand the issue here. 

Again: it's not like when you try to "find" something, type "blah" in the picker, it will create "blah.md". That's not how it works.

**Comment by ernie** [comment]
@renerocksai I understand that it isn't Telescope creating the files. At the very least, GoToDate should have been using `dailies_create_nonexisting` and not the `follow` variant, I believe. The `find` behavior creating the dates seems like a better candidate for `follow`, I think, if that's the intended use case? In any case, I'd turn them all off, personally, but the `GoToDate` behavior was unintuitive.

**Comment by renerocksai** [comment]
So I went through this thread and code again, trying to work out what you were trying to fix. Then, in the discussion,
things seem to have changed. I wasn't sure what should be done now.

First, one more misunderstanding I read in this thread: GotoDate does not always (optionally) create today's note. It
always uses the passed-in date (with today as default if not). On a calendar pick, the calendar's date is used and in
goto_today, today's date is used.

GotoDate isn't used in FindDaily / WeeklyNotes either, so it has no relevance there.

So the only use-cases for GotoDate are:
- picking a date from the calendar 
- calling goto_today

So the only thing I think that can be discussed, is: whether to use `follow_creates_nonexisting` or
`dailies_create_nonexisting` in GotoDate.

Is "clicking" a date in the calendar more like following a link or more like browsing daily notes? I separated
`follow_link` from the dailies/weeklies because the latter are not "taking action on a link" but commands that you
invoke. From that perspective, a calendar action is more similar to following a link that happens to be a date.

The dailies/weeklies options were only meant for: telescope pickers you invoke: should they create today's or this
week's note when you open them? This you can specify in the `dailies/weeklies_create_nonexisting`.

I recommend closing this PR. Most of the code **removes** the ability to create the daily/weekly notes before their
pickers are called. This removes a feature that you can easily disable by setting the corresponding flag to false.

In an unrelated change to GotoDate, GotoDate is made to look for the "wrong" flag IMHO. While it can be discussed which
config option to use here, I explained above how I meant it. 

I think, my original documentation kind of pointed the differences out.

However, recent changes that haven't been reviewed carefully with regards to documentation, introduced a few funny things to the docs:

In the readme, `weeklies_create_nonexisting` became `weekly_create_nonexisting`. In the help file, it became
`weekliesdailies_create_nonexisting`. What's more, the help file suggests that weekly notes can be created when opening
them in the calendar which was never implemented. I think, many good intentions to make the documentation clearer,
changed the meaning a bit - and also changed it differently to readme and help file.

The readme is also wrong with `following a link to a non-existing daily note will create it`.
That's not the case for `dailies_create_nonexisting` but for `follow_creates_nonexisting`. According to git blame, I
have made that mistake myself. So: sorry, I have added my share to the confusion.

So, my suggestion is: let's make the README and help file better, so it's 100% clear what each config option is used
for. If that's too much for the readme, a wiki (which is in the works) and the help file should cover everything. The
help file should always be correct, the source of truth. It's available even when there is no internet connection.

Sorry for going off-topic here a bit. Feel free to submit a revised PR or an issue about the config option, but this one
is confusing.

**Comment by ernie** [comment]
Appreciate the comment. I’m not sure what, if any, thing I can say to clear up the misunderstanding. While Lua’s not my first language, I read the code and I did understand the implementation. I just thought there was no way it could be intentional. 

It sounds like you have very different usage patterns than I do, and I’d be better served by implementing something that works for me specifically. 

Thanks again, and I wish you the best on the project!

**Comment by renerocksai** [comment]
It's fine. I think the misunderstandings have been cleared up now, on both sides :slightly_smiling_face:. From what I understood, the problem at hand should be solvable by setting config options to false. That's what they are here for. To support different usage patterns. So from that perspective, implementing something completely new seems a bit of a stretch to me. So I take it, there's more that doesn't suit your needs. While I would argue that it should be possible to support your specific use cases without breaking the existing ones, maybe introducing additional config options, I'd be interested in what you come up with. The more the merrier :smile:.

**Pull request closed without merging**
