### PR TITLE
fix: Remove CleanPath function, which is causing errors on Windows machines (fixes #151)

### LINKED ISSUE #151: [BUG] path.lua:503: FileNotFoundError
**Please confirm**
- [x] I am running the latest version of this plugin

**Describe the bug**
After installing Telekasten (with the required dependencies, including Plenary and Telescope) using either VimPlug or Packer on Windows 11 and WSL2, and executing `:Telekasten new_note` one gets the following error:

```
Telekasten.nvim: home folder \Users\MyUser\zettelkasten does not exist! Shall I create it? [y/N] yE5108: Error executing lua ...ocal\nvim-data\plugged\plenary.nvim/lua/plenary/path.lua:503: FileNotFoundError
stack traceback:
        [C]: in function 'error'
        ...ocal\nvim-data\plugged\plenary.nvim/lua/plenary/path.lua:503: in function 'mkdir'
        ...cal\nvim-data\plugged\telekasten.nvim/lua/telekasten.lua:245: in function 'check_dir_and_ask'
        ...cal\nvim-data\plugged\telekasten.nvim/lua/telekasten.lua:267: in function 'global_dir_check'
        ...cal\nvim-data\plugged\telekasten.nvim/lua/telekasten.lua:2099: in function 'selection'
        ...cal\nvim-data\plugged\telekasten.nvim/lua/telekasten.lua:3032: in function 'panel'
```

After manually creating the folder and sub-folders (e.g. daily, weekly, etc), one still gets the same error when making news notes. 

`:checkhealth` shows no errors.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start nvim
2. Run `:Telekasten new_note`
3. See prompt "Telekasten.nvim: home folder \User\MyUser\zettelkasten does not exist! Shall I create it? [y/N]"
4. Press "y"
5. See error

**Expected behaviour**
The expected behaviour would be Telekasten creating the zettelkasten home folder. 

**Operating system (please complete the following information):**
 - OS: Windows 11
 - OS: WSL2
 - NVIM: v0.7.0

### PR DESCRIPTION
**Pull request by adrianocorrea**
## Proposed change

Remove the `CleanPath` function, which causes errors for Windows users on Nvim 0.7.0 and Nvim 0.7.2. 
Update `README.md` accordingly to ensure usability. Noted that `~/zettelkasten` syntax also works as expected. 
There is no need to update `doc/telekasten.txt` helpfile, as instructions are still applicable to the plugin.

## Type of change

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Documentation update

## Additional information

- This PR fixes or closes issue: fixes #151
- This PR is related to issue: #151

## Checklist

- [x] I am running the **latest** version of the plugin.
- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [x] The code has been formatted using Stylua (a `.stylua.toml` file is provided)
- [x] The code has been checked with luacheck (a `.luacheckrc` file is provided)
- [x] The `README.md` has been updated according to this change.
- [ ] The `doc/telekasten.txt` helpfile has been updated according to this change.

### CODE REVIEW

**Comment by lambtho12** [comment]
Seems that stylua is not passing. Could you fix that using the config given in `.stylua.toml` at the root of the repo? If for some reason stylua does not work on windows, I can patch the formatting after merge.

**Comment by adrianocorrea** [comment]
I could not reproduce issue #71. I tried setting the home folder using both `init.lua` and `init.vim`, and both worked. Even setting home as "C:\\Users\\myname\\zettelkasten" worked; what does not work is writing it with just a single backslash (i.e. "\") as you need to escape the character for Lua to understand it. Is there a chance that Nvim improved the `vim.fn.expand()` function, fixing the original issue? 

Regarding stylua, I ran the code formatter using ALE and the terminal, and it did not suggest any changes to the submitted file. Analyzing the output of the [failed test](https://github.com/renerocksai/telekasten.nvim/runs/7326801180?check_suite_focus=true), it is flagging changes to lines that I am not sure you want to change (e.g. merging line 740 with 741, 2245 with 2246 and 2247, etc.) and suggesting to replace some code blocks with exact copies (e.g. lines 2786-2793). Note that these are lines that I did not change, so I would not expect formatting errors on them. Thus, if you could please patch the formatting after the merge, it might reduce the chance of breaking the intended code formatting.

**Comment by renerocksai** [comment]
Thanks for this contribution! I am not sure this is the right fix,
though. As you mentioned yourself, `C:\\my\\path` seems to work.
Wouldn't the better fix then be to replace single `\` by `\\`?

That way we wouldn't use the drive letter. I assume, telescope will
always use the disk that the nvim command is executed on. So if you
start it from a console and enter `D: [ENTER]`, then start neovim, it
would search for absolute paths on the D drive.

Oftentimes, people have `D:` drives (or other drives than `C:`) for
data, so that `C:` remains the 'system' drive.

There is a `SUBST` command under DOS that still works. You can use it to
define arbitrary drives for testing:
[subst command](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/subst)

**Comment by adrianocorrea** [comment]
`C:\\my\\path` only works after removing the `CleanPath` function - but not with the current code. Not using double backslash was likely why the user that opened issue #71 could not get Telekasten to work (note that they wrote `C:\Users\...\zettelkasten` on their bug report, using single backslash). Keeping the code prevents a portable configuration between operating systems - preventing the usage of `~/zettelkaten` as the home folder - and results in the reported errors that prevent the plugin usage on Windows. 

The proposed solution allows users to hardcode the `C:\` drive or another drive letter in their home folder or to use the relative path `~`. Note this approach works for plugins as well. For example, one can set the path to vimwiki using `~` on Windows without difficulties.  

However, if there is a better alternative that fixes the current error (allowing Telekasten usage on Windows), let's go for it; just ignore the proposed pull request. Looking forward to the solution.

**Comment by lambtho12** [comment]
I just realized that, according to https://github.com/renerocksai/telekasten.nvim/issues/71#issuecomment-1136991110,  the `CleanPath`function was already not really useful a few months ago...

Just to be sure (as I can not test it myself), with this PR, is it possible for a user to write:
- [ ] `C:\\my\\path`
- [ ] `D:\\my\\other\\path`
- [ ] `C:/my/path`
- [ ] `D:/my/other/path`
- [ ] `~/my/path`

If all these are good, I don't see an issue with merging this.

**Comment by adrianocorrea** [comment]
That is correct. All these alternatives will work:
- [x] `C:\\my\\path`
- [x] `D:\\my\\other\\path`
- [x] `C:/my/path`
- [x] `D:/my/other/path`
- [x] `~/my/path`

What will not work is `/Users/myuser/zettelkasten` on Windows (as the root directory in Windows is not called `\`), but `/home/myuser/zettelkasten` will work on Linux.

For the documentation, the `~/zettelkasten` will work on Unix-like systems and Windows, but if you want something that is Windows-specific, `C:\\Users\\youruser\\zettelkasten` or `C:/Users/youruser/zettelkasten` are good alternatives.

I hope this helps. 

Thank you very much for the timely and helpful support. This plugin is fantastic and developing well. I believe it not only provides an invaluable tool for people that uses a Zettelkasten, but might also become the go-to alternative in Lua to replace VimWiki - we only need to implement a home directory switcher that works as a selector for the desired "wiki".

**Comment by lambtho12** [comment]
@renerocksai , do you have any reason not to merge this? It seems to allow all possible path types for windows-specific users, while allowing them to refer to other disks than `C:`as well. I don't think it should break anyone's config either.

**Comment by renerocksai** [comment]
I must have misunderstood a bunch here. I was of the impression that drive letters would be problematic with this PR.

Thanks for pointing it out so clearly now - and your patience :+1:

**Comment by renerocksai** [comment]
I should have checked the PR. You committed **your** README, which makes sense, but not in the PR.

**Comment by renerocksai** [comment]
Having said all that, what probably didn't get through between the lines:

THANK YOU FOR YOUR CONTRIBUTION! 

It is especially valuable as it's really hard for me to test things out on Windows. There are Windows users out there and I bet they will be thankful, too! :clap:

**Comment by adrianocorrea** [comment]
It's my pleasure. I am happy this worked out. 😄 

Thank you for putting together this awesome plugin, and feel free to reach me if you need further assistance in testing it on cross-platform environments.

**Pull request merged**
