### PR TITLE
Multiple home directory

### LINKED ISSUE #155: [FR] Home folder switcher
**Please confirm**
- [x] I am running the latest version of this plugin

**Is your feature request related to a problem? Please describe.**
The release of Vim9 might become a fork in the road for Vim and Nvim users and plugin developers. Vim9 comes with Vim9script, a scripting language not supported by Nvim (see the [Nvim's non-goals](https://neovim.io/charter/)). Therefore, when some plugins start migrating from vimscript to Vim9script, they will no longer work on Nvim. 

A popular plugin is [VimWiki](https://vimwiki.github.io/), originally released on May 4, 2008. It has over 7.4k stars on GitHub and many users. VimWiki was also a solution for people that wanted to implement a Zettelkasten in Vim in the past. 

Due to VimWiki's legacy code base, the project is unlikely to be ported to Lua. However, Telekasten is already an alternative to VimWiki, once:

* Note creation and links work similarly between the two plugins.
* Search and back-links exist already in Telekasten.
* Tags used in VimWiki are supported in Telescope and Telekasten.
* To-do lists and diaries are already implemented in Telekasten.
* While VimWiki allows three different syntaxes, most users no longer use vimwiki's or WikiMedia's syntaxes. Instead, people are using markdown, which Telekasten uses as well.
* While VimWiki has a shortcut for the `index` note, the user can easily search for it in Telekasten.

Thus, Telekasten is a viable alternative to VimWiki for Nvim users (especially users that want a full-Lua Nvim configuration).

That said, VimWiki has one key feature missing in Telekasten: the ability to have multiple "Wikis". However, by implementing a dictionary (or list) of `home` folders - instead of using a single value for it - and adding a selector (which is `<leader>ws` on VimWiki), this limitation is removed. This feature might also be valuable for people that do not use VimWiki but would like to isolate their Zettelkasten note cards. For example, one might want to have one for business and another for academic work - or even one where they keep joke ideas only. Different Zettelkastens can also be used to isolate notes from unrelated projects, especially when working with other team members that should not have access to one's personal diary notes. 

**Describe the solution you'd like**
Implement the `home` variable as a dictionary of `home` folders, where each value comprises (a) the Zettelkasten name (i.e. what the user decides to call it) and (b) the path to the note repository. If the user does not set a home folder dictionary, the home folder value defaults to `{"Zettelkasten": "~/zettelkasten"}` (or something similar).

There should also be a function that allows the selection of which Zettelkasten one wants to open. It could be a fuzzy finder or a list of the keys in the home dictionary. Users may assign the function to keybindings for ease of access. 

**Describe alternatives you've considered**
* Keep using VimWiki.
* Change the `home` variable manually every time when one wants to change Zettelkastens.

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by shivanth**
## Proposed change

1. Borrow the concept of vaults from Obsidian. Vaults correspond to different base directories in Telekasten.
2. Let user configure multiple vaults using `setup`.
3. Provide `switch_vault()` for user to switch to a new vault via telescope picker. The picker lists all the vaults configured in config. 
4. Make the changes backward compatible. Users should not have to change their config if they update to the latest version.
## Type of change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Code quality improvements to existing code or addition of tests
- [x] Documentation update

## Additional information

- This PR fixes or closes issue: fixes #155
- This PR is related to issue:

## Checklist

- [x] I am running the **latest** version of the plugin.
- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [x] The code has been formatted using Stylua (a `.stylua.toml` file is provided)
- [x] The code has been checked with luacheck (a `.luacheckrc` file is provided)
- [x] The `README.md` has been updated according to this change.
- [x] The `doc/telekasten.txt` helpfile has been updated according to this change.

### CODE REVIEW

**Comment by shivanth** [comment]
Ping @renerocksai . Is telekasten still managed on github ?

**Comment by lambtho12** [comment]
Thank you for your awesome work on this long-awaited feature. I am currently in vacation and won't have time to review that before the end of the month. Hopefully Rene will have time to do it before.

> Is telekasten still managed on github ?

Currently the Github repo is similar to [the one on SourceHut](https://sr.ht/~renerocksai/telekasten.nvim/). The main differences are the documentation and wiki that have been slightly modified on SH to prepare the transition and the archival of the Github's version. Currently, we still accept issues and PR here and port them to the SH's repo to keep the code bases in sync. This PR might be the last one here though.
I suggest you send a mail to the [telekasten-devel](https://lists.sr.ht/~renerocksai/telekasten.nvim-devel) mailing list to make sure Rene gets notified of this awesome PR. This might speed up the integration of the feature.

---
Once again thank you very much for your work!

**Comment by renerocksai** [comment]
Wow, thanks a lot for this PR! I have skimmed over it and it looks fine, apart
from formatting issues. Your formatting changes make it difficult to find the
actually meaningful changes as opposed to whitespace changes. Are you sure you
used the provided stylua config?

Anyways, I'll go and apply this for a quick test (see below).

@lambtho12 is correct. We're still on GitHub. After merging this PR, I'm also
going to apply it to the SourceHut repo, and once we've switched over, we'll
likely apply patches from SourceHut to the GitHub repo, for a brief while.

BTW: If you add `.patch` to the PR URL, you get a nicely formatted patch:

<https://patch-diff.githubusercontent.com/raw/renerocksai/telekasten.nvim/pull/158.patch>

Curling the patch and piping it to `git am` is super easy. :relaxed: - well,
usually. Unfortunately, you using tabs and spaces, this somehow makes git
complain. So I had to re-format the patch to make it apply in order to briefly smoke-test it.

During the smoke-test, I noticed a bug: if you don't have a vault configured,
the setup() breaks when you write to M.vaults["default"]. This immediately
breaks everyone's telekasten when they update their telekasten to this PR, since
probably noone will have prepared for the update with a `vaults` section in
their configs.

Luckily, it is easily solved:

```lua
M.vaults = cfg.vaults or {}  -- notice the `or {}`
```

Here it is in diff format:

```diff
@@ -2937,7 +2937,7 @@ local function _setup(cfg)
         cfg.vaults = nil
         Setup(cfg.vaults["default"])
     elseif cfg.home ~= nil then

-        M.vaults = cfg.vaults
+        M.vaults = cfg.vaults or {}
         cfg.vaults = nil
         M.vaults["default"] = cfg
         Setup(cfg)
```

I guess, in this else branch, cfg.vaults is always nil at the beginning, so,
arguably, you coud probably set `M.vaults = {}` here unconditionally. But maybe
I'm wrong, so the `or {}` is the safest option :smile:.

So, may I please ask you to:

- make sure you convert tabs to spaces
    - I substituted them by 4 spaces YMMV
- to please use the provided `stylua.toml`
- add the `or {}`

Then I'll happily merge.

Thanks again for the great PR!

**Review by renerocksai — CHANGES_REQUESTED** [review]
Please see my longer comment

**Comment by shivanth** [comment]
I am using stylua. 
```
stylua lua/telekasten.lua -f .stylua.toml

```

I'm using stylua version 

```
 stylua --version
stylua 0.14.2
``` . 

I wonder what is missing.

**Comment by renerocksai** [comment]
> I am using stylua.
>
> ``` stylua lua/telekasten.lua -f .stylua.toml ```
>
> stylua version
>
> ``` $stylua --version stylua 0.14.2 ```
>
> I wonder what is missing.

I know it now! The patch breaking has nothing to do with your setup! The TAB was
in there when you cloned already!

image

And the source of all the problems seems to be:

image

ME!  😱 I hate it when that happens.... 😀

Sorry for having blamed you. Your PR diff shows so many red followed by green
lines that are identical apart from whitespace changes that I automatically
thought everything whitespace related must be rooted in the PR. IDK how I could
have introduced a tab since I don't use tabs and my vim is configured not to use
them either.

>
> Meanwhile, let me try to change the tab configuration of my editor.

Not necessary.

The reason stylua did not catch this tab is because it's not considered an
indendation when it happens inside a comment.

So, if you don't mind, can you replace the tab in line 930 with 4 spaces to make
the patch more git-friendly (it doesn't like a mix of tabs and spaces in the
same line apparently)?

Everything else looks fine apart from me still wondering why there are so many
whitespace changes. If you've tested it and it works, it looks pretty
merge-able to me.

**Comment by renerocksai** [comment]
> So, if you don't mind, can you replace the tab in line 930 with 4 spaces to 
> make the patch more git-friendly (it doesn't like a mix of tabs and spaces in 
> the same line apparently)?

You know what, forget that. No need to fix what I caused.

As soon as I have your OK that the PR is good to go, I'll apply your PR with a
fixed-up patch, re-format everything with stylua just to be sure, and commit +
push everything referencing the PR, then close the PR.

Tell me when ready.

**Comment by shivanth** [comment]
Sure, go ahead !

**Comment by renerocksai** [comment]
So, I did the following:

- squashed all 4 PR commits into one single commit
- ran `stylua -f .stylua.toml` on both `telekasten.lua` and `vaultpicker.lua`.
- got rid of TABs in `doc/telekasten.txt` and `README.md`
- committed the tabs + formatting changes
- squashed the PR commit and fixup commit into a single commit again

Now the diff is significantly smaller, no only-whitespace changes in unrelated
areas.

Just FYI if I do the following:

```
cd lua
nvim telekasten.lua
```

... and save the file, my `stylua` plugin will run, but not find a
`.stylua.toml`, because that's in the root dir of the plugin, not in the `lua/`
dir - and hence stylua will apply default formatting, which is inconsistent with
`.stylua.toml` and lead to lots of unintended re-formatting.

But since there were tabs in all files you touched, you clearly seem to like
them or something is going on... 😊

For potential future contributions, please make sure that you:

- search for `\t` before you save and quit and fix any tabs into spaces
- run stylua right before you commit, on ALL files you commit, not just
  `telekasten.lua`.

Some more nitpicking: in the README, there is a table explaining all config
settings - as a sort of single point of reference. If you feel inclined, you
might want to update this section, too, for the sake of consistence. I noticed
that the previous introduction to the settings also didn't do this, but I think
that table shouldn't be incomplete. Some people use the table to look stuff up.

There's only one more thing to say:

**THANKS A MILLION FOR THIS GREAT AND LONG-AWAITED FEATURE!**

I am sure, many telekasten users out there will love it!

**Pull request closed without merging**
