### PR TITLE
Add an Agenda of TODOs that can be quickly edited and viewed.

### PR DESCRIPTION
**Pull request by alex-laycalvert**
## Proposed change

***NOT READY TO MERGE***

This PR will add an `agenda` to `telekasten.nvim` that is a list of TODOs that a user can view and edit. Currently all this PR does is let you call `open_agenda` which will open an `agenda.<ext>` file in your `home` directory for telekasten and create it if necessary. The `show_agenda` command prints out every TODO item in the `agenda` file to neovim's normal text output. 

I know that `telekasten.nvim` is about notetaking but personally I see my agenda of TODOs as part of my notes since normally I need to use it to look at things like due dates and other things like that. Perfectly fine if this is not something that should be implemented since I know there are other plugins that do this but I think it would be more natural if it was builtin.

I want to add more to this PR so that you can use a `telescope` picker to view all of your TODOs that would open a buffer and show you any information you listed with the TODO.

So if your agenda was like this:

```markdown
# TODOs

- [ ] Do a thing
  - General information about this TODO
  - [ ] Subtask for "Do a thing" 
- [ ] Do another thing
  - Some more general information
```

Then picking the TODO `Do a thing` from a picker would show you

```markdown
- [ ] Do a thing
  - General information about this TODO
  - [ ] Subtask for "Do a thing" 
```

And allow you to edit the status or info of that TODO from the window.

Another feature that could be worked on is added a deadline to each TODO like in orgmode where there would be some fancy format to make sure you know when you need to complete each item. It would be nice if this could also be shown on the calendar as well.

Let me know if there's any info you want from me on my thought process for this or if this is just not something that could/should be a part of this plugin.

Thanks.

## Type of change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (thank you!)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Documentation update

## Additional information

Not all of the requirements have been checked since this is not what I would consider a production ready PR. I wanted to get the idea out there to get some feedback.

## Checklist

- [x] I am running the **latest** version of the plugin.
- [x] The code change is tested and works locally. (Feature not fully implemented)
- [x] There is no commented out code in this PR.
- [ ] The code has been formatted using Stylua (a `.stylua.toml` file is provided)
- [ ] The code has been checked with luacheck (a `.luacheckrc` file is provided)
- [ ] The `README.md` has been updated according to this change.
- [ ] The `doc/telekasten.txt` helpfile has been updated according to this change.

### CODE REVIEW

**Comment by lambtho12** [comment]
First of all, thank you very much for your contribution and your desire to help improving Telekasten with great features.

Regarding this PR, I am personally not a fan of integrating more advanced task features in Telekasten. 
For me, Telekasten is first and foremost a note-taking plugin. Sure it can support basic features, but trying to integrate complex task management inside telekasten will make it a nightmare to maintain in the long run (I fear so). I may be wrong and there seems to be some support for this feature (#159), so I try to keep an open mind.

I also think that there are already extremely nice and powerful tools for task management. My favorite is [taskwarrior](https://taskwarrior.org/). There is also a [plugin to interface taskwarrior with vimwiki](https://github.com/tools-life/taskwiki). I think advanced task features in telekasten should be implemented in a similar way. Maybe not rely on taskwarrior, but as a separate plugin that interfaces with telekasten.

Obviously this is just my personal opinion. I would very much like to hear @renerocksai's opinion on that matter.

**Comment by alex-laycalvert** [comment]
Completely understandable, it would make sense to just create interfaces for telekasten to talk to other plugins that way you kind of get their features "for free" instead of reinventing the wheel.

**Comment by alex-laycalvert** [comment]
I also see the previous response to an issue like this, didn't comb the previous PRs and issues that deep.

**Comment by alex-laycalvert** [comment]
I'm going to take a look at `taskwarrior` and see how I like it.

**Comment by lambtho12** [comment]
> I'm going to take a look at `taskwarrior` and see how I like it.

Check out [vit](https://github.com/vit-project/vit) as well. This is a visual interface (still terminal based) to taskwarrior.
I personally use this quite a lot to manage all my tasks according to the GTD principles.

**Comment by alex-laycalvert** [comment]
This probably isn't going to go anywhere so I'll go ahead and close it. Gives me an opportunity to make my own TODO handling system though, I've been looking for new project ideas.

**Pull request closed without merging**
