### PR TITLE
fix: note title ending removed when it matches parts of extension

### LINKED ISSUE #118: [BUG] Note title ending removed when it matches parts of extension
**Please confirm**
- [x] I am running the latest version of this plugin

**Describe the bug**
`telekasten.lua` on HEAD uses the following gsub expr to parse a title given to new notes:
`"[" .. M.Cfg.extension .. "]+$"`

- [CreateNoteSelectTemplate](https://github.com/renerocksai/telekasten.nvim/blob/10df87abae2b04d7b2d0771a96f94d70bc94f3ff/lua/telekasten.lua#L1997)
- [CreateNote](https://github.com/renerocksai/telekasten.nvim/blob/10df87abae2b04d7b2d0771a96f94d70bc94f3ff/lua/telekasten.lua#L2074)

**To Reproduce**

1. Either use default config (`.md`) or account for extension setting in following steps
2. Start nvim
3. Create a new note - `:lua require('telekasten').new_note()`
4. Provide a title like "Neovim"
5. Observe that the created note is called "Neovi"

**Expected behavior**

A note file named "Neovim.md" to be created

**Screenshots**

image

**Operating system (please complete the following information):**

OS: using Linux & Mac; should affect any, not OS specific

**Additional context**

I assume the intent is to allow multiple captures of something like `NoteTitle.md.md` and to chop them off. By using `[]` it's a character set rather than a direct match with `()`. Lua patterns don't allow N-captures with `()`, though. So from my PoV the choice is to continue chopping the end off if it matches the extension.

Will submit a PR shortly.

### PR DESCRIPTION
**Pull request by chrsm**
By using [] we provide a character set rather than a direct match with ().

fixes #118

## Proposed change

When creating a note title, replace only the last occurrence of an extension configured by the user (i.e. Filename.md -> Filename, Filename.md.md -> Filename.md).

## Type of change

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (thank you!)
- [ ] Code quality improvements to existing code or addition of tests
- [ ] Documentation update

## Additional information

- This PR fixes or closes issue: fixes #118 
- This PR is related to issue: #118 

## Checklist

- [x] I am running the **latest** version of the plugin.
- [x] The code change is tested and works locally.
- [x] There is no commented out code in this PR.
- [x] The code has been formatted using Stylua (a `.stylua.toml` file is provided)
- [x] The code has been checked with luacheck (a `.luacheckrc` file is provided)
- [ ] The `README.md` has been updated according to this change.
- [ ] The `doc/telekasten.txt` helpfile has been updated according to this change.

## Notes

Re: checklist - I am not sure if there's anything to do w/r/t the README or doc. I don't see a changelog so I assume we are all good there.

### CODE REVIEW

**Comment by lambtho12** [comment]
> Lua patterns don't allow N-captures with ()

Are you sure?

In f17d5b3 I solved basically the same issue and it seems to be working fine by just swapping the square brackets with parentheses.

**Comment by chrsm** [comment]
@lambtho12

1. I don't think it _is_ useful. I guess if a user really, really wants to add a `.md` to the end of their note, they should be able to? I also agree that I don't think anyone will actually do that in practice.
2. I'm happy to add a `stripextension` and make it a single-replace.

I'll push up a change in a few minutes here.

**Comment by chrsm** [comment]
I've pushed another commit. This one does a single replace, so `FilenameTest_md.md.md` -> `FilenameTest_md.md` as expected, `Filename_md` -> `Filename_md` as expected (etc).

I don't know how you prefer to merge, let me know if you would like me to squash these into one commit.

**Comment by lambtho12** [comment]
Awesome! Thank you very much

**Pull request merged**
